# Generated by Django 5.0.3 on 2024-03-31 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(help_text='Password must have an uppercase, lowercase, number and special characters. 12-25 characters long.', max_length=150, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z'), django.core.validators.MinLengthValidator(limit_value=12, message='The password must be more than 12 characters long.'), django.core.validators.MaxLengthValidator(limit_value=25, message='The password must be less than 25 characters long.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z')]),
        ),
    ]
